version: "3.9"
services:
  web:
    build: .
    env_file: .env
    restart: always
    networks: [appnet]
  worker:
    build: .
    env_file: .env
    command: ["python","-m","app.worker"]
    restart: always
    networks: [appnet]
  nginx:
    image: nginx:stable
    volumes:
      - ./ops/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports: ["80:80","443:443"]
    depends_on: [web]
    restart: always
    networks: [appnet]
networks:
  appnet:
